# Generated by Django 2.1.7 on 2019-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0002_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/images/1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
