# Generated by Django 2.1.7 on 2019-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0008_recipe_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingred',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred',
            field=models.TextField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingred',
        ),
    ]
